### ISSUE TITLE
Changelog no longer saved to GitLab registry

### ISSUE THREAD

**Issue by aodendaal** [semantic-release/changelog#396] opened 2024-07-16 10:21 UTC
I have a project that added a changelog.md to the GitLab registry on 25 June 2024 but since 1 July 2024 without changing the semantic release or GitLab CI pipeline a release is created with a new git tag but the file give 404 in the registry and the log says uploaded file.

I tried re-creating and applying the Access Token but the issue still occurs; and semantic release but be using it because it can create a release and git tag.

Here is my GitLab CI (.gitlab-ci.yml)
```
create_release:
  stage: deploy
  image: node:21.6.2
  before_script:
    - npm install -g semantic-release@23 @semantic-release/changelog@6 @semantic-release/gitlab@13
  script:
    - npx semantic-release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
```

my release pipeline (.releaserc)
```
{
    "branches": ["main"],
    "tagFormat": "${version}",
    "plugins": [
        "@semantic-release/commit-analyzer",
        "@semantic-release/release-notes-generator",
        [
          "@semantic-release/changelog",
          {
            "changelogFile": "CHANGELOG.md"
          }
        ],
        [
            "@semantic-release/gitlab",
            {
              "gitlabUrl": "https://gitlab.com",
              "assets": [
                { "label" : "Changelog", "path" : "CHANGELOG.md"}
              ]
            }
          ]
    ]
}
```

and my build log
```
Running with gitlab-runner 17.0.0~pre.88.g761ae5dd (761ae5dd)
  on green-3.saas-linux-small-amd64.runners-manager.gitlab.com/default Jhc_Jxvh, system ID: s_0e6850b[2](https://gitlab.com/andre3254704/test-demo/-/jobs/7351701263#L2)bce1
Preparing the "docker+machine" executor
00:21
Using Docker executor with image node:21.6.2 ...
Pulling docker image node:21.6.2 ...
Using docker image sha256:1b9d5f[3](https://gitlab.com/andre3254704/test-demo/-/jobs/7351701263#L3)b36bfd39fa919ff2ef7fbcc5ee6b983b2c40d558208a5[4](https://gitlab.com/andre3254704/test-demo/-/jobs/7351701263#L4)9428074a42e for node:21.6.2 with digest node@sha2[5](https://gitlab.com/andre3254704/test-demo/-/jobs/7351701263#L5)6:65998e325b06014d4f1417a8a6afb1540d1ac[6](https://gitlab.com/andre3254704/test-demo/-/jobs/7351701263#L6)6521cca76f2221a6953947f9ee ...
Preparing environment
00:06
Running on runner-jhcjxvh-project-57106836-concurrent-0 via runner-jhcjxvh-s-l-s-amd64-1721124355-68c3647b...
Getting source from Git repository
00:02
Fetching changes with git depth set to 20...
Initialized empty Git repository in /builds/andre3254[7](https://gitlab.com/andre3254704/test-demo/-/jobs/7351701263#L7)04/test-demo/.git/
Created fresh repository.
Checking out 1d2b0e2b as detached HEAD (ref is main)...
Skipping Git submodules setup
$ git remote set-url origin "${CI_REPOSITORY_URL}"
Executing "step_script" stage of the job script
00:21
Using docker image sha256:1b9d5f3b36bfd39fa919ff2ef7fbcc5ee6b9[8](https://gitlab.com/andre3254704/test-demo/-/jobs/7351701263#L8)3b2c40d558208a549428074a42e for node:21.6.2 with digest node@sha256:65998e325b06014d4f1417a8a6afb1540d1ac66521cca76f2221a6[9](https://gitlab.com/andre3254704/test-demo/-/jobs/7351701263#L9)53947f9ee ...
$ npm install -g semantic-release@23 @semantic-release/changelog@6 @semantic-release/gitlab@13
npm WARN deprecated read-pkg-up@11.0.0: Renamed to read-package-up
added 371 packages in [10](https://gitlab.com/andre3254704/test-demo/-/jobs/7351701263#L10)s
102 packages are looking for funding
  run `npm fund` for details
$ npx semantic-release
[10:08:53 AM] [semantic-release] › ℹ  Running semantic-release version 23.1.1
[10:08:53 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[10:08:53 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
[10:08:53 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[10:08:53 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[10:08:53 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[10:08:53 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[10:08:53 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/gitlab"
[10:08:53 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/gitlab"
[10:08:57 AM] [semantic-release] › ✔  Run automated release from branch main on repository https://gitlab.com/andre3254704/test-demo
[10:08:57 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[10:08:57 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[10:08:57 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[10:08:57 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
[10:08:57 AM] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (https://gitlab.com/api/v4)
[10:08:57 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/gitlab"
[10:08:57 AM] [semantic-release] › ℹ  Found git tag 1.[12](https://gitlab.com/andre3254704/test-demo/-/jobs/7351701263#L12).0 associated with version 1.12.0 on branch main
[10:08:57 AM] [semantic-release] › ℹ  Found 1 commits since last release
[10:08:57 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[10:08:57 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat: update text
[10:08:57 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[10:08:57 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 1 commits complete: minor release
[10:08:57 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[10:08:57 AM] [semantic-release] › ℹ  The next release version is 1.[13](https://gitlab.com/andre3254704/test-demo/-/jobs/7351701263#L13).0
[10:08:57 AM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[10:08:57 AM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[10:08:57 AM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/changelog"
[10:08:57 AM] [semantic-release] [@semantic-release/changelog] › ℹ  Update /builds/andre3254704/test-demo/CHANGELOG.md
[10:08:57 AM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/changelog"
[10:08:59 AM] [semantic-release] › ✔  Created tag 1.13.0
[10:08:59 AM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/gitlab"
[10:09:00 AM] [semantic-release] [@semantic-release/gitlab] › ℹ  Uploaded file: /uploads/523935bb6[14](https://gitlab.com/andre3254704/test-demo/-/jobs/7351701263#L14)ec1406c95e4d24b17c3a2/CHANGELOG.md
[10:09:01 AM] [semantic-release] [@semantic-release/gitlab] › ℹ  Published GitLab release: 1.13.0
[10:09:01 AM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/gitlab"
[10:09:01 AM] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/gitlab"
[10:09:01 AM] [semantic-release] › ✔  Completed step "success" of plugin "@semantic-release/gitlab"
[10:09:01 AM] [semantic-release] › ✔  Published release 1.13.0 on default channel
Cleaning up project directory and file based variables
00:01
Job succeeded
```

**Comment by travi** [comment] 2024-08-02 21:44
closing as duplicate of https://github.com/semantic-release/gitlab/issues/750

**Closed by travi** 2024-08-02 21:44 UTC
